// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4tIJSWY3FuEWYONPyFjryVjJpSBewkUc',
    appId: '1:618951408840:web:4ecc7bca8f3525d3a479fd',
    messagingSenderId: '618951408840',
    projectId: 'ecommerce-flutter-b8edd',
    authDomain: 'ecommerce-flutter-b8edd.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-b8edd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjTKgD1YgUt1UK5_3dlNAjZL4KlYpUQI0',
    appId: '1:618951408840:android:81caf921863ba027a479fd',
    messagingSenderId: '618951408840',
    projectId: 'ecommerce-flutter-b8edd',
    storageBucket: 'ecommerce-flutter-b8edd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFLE1Us8YYjgo_TbwTMKYQiWGBtqnAk-0',
    appId: '1:618951408840:ios:9c8c95a47a88841ba479fd',
    messagingSenderId: '618951408840',
    projectId: 'ecommerce-flutter-b8edd',
    storageBucket: 'ecommerce-flutter-b8edd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );
}
